version: '3'
services:
    database:
        build: ./init/mysql
        container_name: mysql
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: 'hdcevents'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - ./init/mysql/dbdata:/var/lib/mysql

networks:
  php-database-test:
    external: true




